name: nFootcube
version: 1.0.0-b330
authors:
  - SmileyCraft
  - Neeonn
main: io.github.divinerealms.footcube.Footcube
api-version: 1.8
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  footcube:
    description: Base command for Footcube.
    aliases: [fc]
  commandDisabler:
    description: Base command for Command Disabler.
    aliases: [cd]
  cube:
    description: Spawn cubes.
  clearcube:
    description: Clear nearest cube.