name: nFootcube
version: 1.0.0-b174
authors:
  - SmileyCraft
  - Neeonn
main: io.github.divinerealms.footcube.Footcube
softdepend:
  - Vault
commands:
  nfootcube:
    description: Base command for Footcube.
    aliases: [nfc]
  cube:
    description: Spawning a ball.
  clearcube:
    description: Removes the nearest ball.