name: nFootcube
version: 1.0.0-b322
authors:
  - SmileyCraft
  - Neeonn
main: io.github.divinerealms.footcube.Footcube
api-version: 1.8
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  nfootcube:
    description: Base command for Footcube.
    aliases: [nfc]