# =================================================================================================
#
#      __      ooooooooooo                       o8                        oooo
#   .'".'"'.    888    88 ooooooo     ooooooo  o888oo ooooooo  oooo  oooo   888ooooo    ooooooooo
#  :._.""._.:   888     888     888 888     888 888 888         888   888   888    888 888     888
#  :  \__/  :   888ooo8 888     888 888     888 888 888         888   888   888    888 888oooooo88
#   './  \.'    888     888     888 888     888 888 888         888   888   888    888 888
#      ""      o888o      88ooo88     88ooo88    888o 88ooo888   888o88 8o o888ooo88     88oooo888
#
# =================================================================================================

# -------------------------------------------------------------------------------------------------
# Settings for the ball (cube).
# -------------------------------------------------------------------------------------------------
cube:

  # Control the power limit.
  # Changing these values results in balls being able to travel further away from a single hit.
  power-limit:

    # Kicking power when not using shift or charging for less than 4 dots (XP Bar).
    # Default value: 2.0
    regular-kick: 2.0

    # Kick Power whilst shifting.
    # Default value: 1.0
    charged-kick: 1.0

    # Default value is half of the xp bar (4.0).
    total-kick-power: 4.0

  # Control the kick power.
  # Changing this value increases the strenght of the kick.
  #
  # Default value: 1.0
  kick-power: 1.0

  # Settings for entity effect.
  # This setting can be toggled and will only work after a server restart.
  effect:
    enabled: false

    # List of effects: DEATH, FIREWORK_EXPLODE, HURT, IRON_GOLEM_ROSE, SHEEP_EAT, VILLAGER_ANGRY
    # VILLAGER_HAPPY, VILLAGER_HEART, WITCH_MAGIC, WOLF_HEARTS, WOLF_SHAKE, WOLF_SMOKE,
    # ZOMBIE_TRANSFORM.
    type: HURT

  # Choose your own sound for when a player interacts with a ball.
  # This setting can be toggled and will only work after a server restart.
  #
  # List of available sounds: https://www.andre601.ch/Spigot-Sounds/sounds/mc-1.8/
  sounds:
    enabled: true

    # Sound when moving the ball with the body and/or right-clicking it.
    move: SLIME_WALK

    # Sound when kicking the ball.
    kick: SUCCESSFUL_HIT

  # The radius that is used to remove balls using the "clearcube" command.
  remove-distance: 100

  # How long should players wait between each ball spawn (in seconds)?
  spawn-cooldown: 15

  # What should the ball hit cooldown be (in milliseconds)?
  kick-cooldown:
    enabled: true
    cooldown: 250



# -------------------------------------------------------------------------------------------------
# Toggle debug for more informations.
# -------------------------------------------------------------------------------------------------
debug:
  ball-hits: false